services:
  server:
    build: ./service
    ports:
      - "8080:8080"
    container_name: eu-fx-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
